"""Add employment type model and relationship to Employee

Revision ID: 2d6271314d2a
Revises: 9f0cedf175eb
Create Date: 2025-11-01 21:15:01.310539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d6271314d2a'
down_revision = '9f0cedf175eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employment_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employment_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_employee_employment_type_id', 'employment_type', ['employment_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint('fk_employee_employment_type_id', type_='foreignkey')
        batch_op.drop_column('employment_type_id')

    op.drop_table('employment_type')
    # ### end Alembic commands ###
