"""Organized HR and Payroll relationships

Revision ID: 3ee2e79b7387
Revises: 6d16910728ee
Create Date: 2025-10-21 12:37:39.330505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee2e79b7387'
down_revision = '6d16910728ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_allowances', schema=None) as batch_op:
        batch_op.drop_column('date_assigned')
        batch_op.drop_column('active')
        batch_op.drop_column('custom_amount')
        batch_op.drop_column('custom_percentage')

    with op.batch_alter_table('employee_deductions', schema=None) as batch_op:
        batch_op.drop_column('date_assigned')
        batch_op.drop_column('active')
        batch_op.drop_column('custom_amount')
        batch_op.drop_column('custom_percentage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_deductions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_percentage', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('custom_amount', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('date_assigned', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('employee_allowances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_percentage', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('custom_amount', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('date_assigned', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
