"""Fix duplicate relationship User-Leave

Revision ID: 4bf5366010d8
Revises: 749ec7193d5d
Create Date: 2025-09-13 12:46:26.792629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf5366010d8'
down_revision = '749ec7193d5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.drop_column('leave_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leave_type', sa.VARCHAR(length=50), nullable=False))

    op.drop_table('leave_type')
    # ### end Alembic commands ###
