"""Fix Leave.leave_type_id FK name

Revision ID: 681775dffa8c
Revises: 64ef5dca3a7b
Create Date: 2025-09-13 13:50:05.835533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681775dffa8c'
down_revision = '64ef5dca3a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leave_type_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_leave_leave_type_id', 'leave_type', ['leave_type_id'], ['id'])
        batch_op.drop_column('leave_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leave_type', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint('fk_leave_leave_type_id', type_='foreignkey')
        batch_op.drop_column('leave_type_id')

    # ### end Alembic commands ###
