"""Add employee-allowance and employee-deduction relationships

Revision ID: 6d16910728ee
Revises: 
Create Date: 2025-10-21 11:37:54.464551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d16910728ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('_alembic_tmp_payroll')
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.alter_column('basic_salary',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('gross_pay',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('net_pay',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('payslip', schema=None) as batch_op:
        batch_op.alter_column('payslip_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('basic_salary',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('gross_pay',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('net_pay',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payslip', schema=None) as batch_op:
        batch_op.alter_column('net_pay',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('gross_pay',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('basic_salary',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('payslip_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.alter_column('net_pay',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('gross_pay',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('basic_salary',
               existing_type=sa.FLOAT(),
               nullable=True)

    op.create_table('_alembic_tmp_payroll',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('pay_period_id', sa.INTEGER(), nullable=False),
    sa.Column('pay_period_start', sa.DATE(), nullable=False),
    sa.Column('pay_period_end', sa.DATE(), nullable=False),
    sa.Column('basic_salary', sa.FLOAT(), nullable=False),
    sa.Column('overtime_hours', sa.FLOAT(), nullable=True),
    sa.Column('overtime_pay', sa.FLOAT(), nullable=True),
    sa.Column('holiday_pay', sa.FLOAT(), nullable=True),
    sa.Column('night_differential', sa.FLOAT(), nullable=True),
    sa.Column('gross_pay', sa.FLOAT(), nullable=False),
    sa.Column('sss_contribution', sa.FLOAT(), nullable=True),
    sa.Column('philhealth_contribution', sa.FLOAT(), nullable=True),
    sa.Column('pagibig_contribution', sa.FLOAT(), nullable=True),
    sa.Column('tax_withheld', sa.FLOAT(), nullable=True),
    sa.Column('other_deductions', sa.FLOAT(), nullable=True),
    sa.Column('total_deductions', sa.FLOAT(), nullable=True),
    sa.Column('net_pay', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['pay_period_id'], ['payroll_period.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
