"""Add department_id to User

Revision ID: 749ec7193d5d
Revises: d9df7bbdefbd
Create Date: 2025-09-11 15:47:49.024581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749ec7193d5d'
down_revision = 'd9df7bbdefbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_user_department_id',   # 👈 give the constraint a name
            'department',              # referenced table
            ['department_id'],         # column in user
            ['id']                     # column in department
        )
        batch_op.drop_column('department')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_user_department_id', type_='foreignkey')  # 👈 match the name
        batch_op.drop_column('department_id')
    # ### end Alembic commands ###
