"""Add approval fields to Payslip model

Revision ID: 887368c186c8
Revises: 3ee2e79b7387
Create Date: 2025-10-24 18:13:12.919376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887368c186c8'
down_revision = '3ee2e79b7387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payslip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payslip', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by')

    # ### end Alembic commands ###
