"""Add claimed field to payslip

Revision ID: 88e4d7bd8262
Revises: 887368c186c8
Create Date: 2025-10-27 17:00:57.270661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e4d7bd8262'
down_revision = '887368c186c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payslip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claimed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payslip', schema=None) as batch_op:
        batch_op.drop_column('claimed')

    # ### end Alembic commands ###
