"""Add employment type model and relationship to Employee

Revision ID: 95bb6eb72a3f
Revises: 2d6271314d2a
Create Date: 2025-11-02 21:41:44.289081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95bb6eb72a3f'
down_revision = '2d6271314d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('working_hours', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('working_hours')

    # ### end Alembic commands ###
