"""Added working_hours and calculation method to Payroll

Revision ID: 9f0cedf175eb
Revises: 88e4d7bd8262
Create Date: 2025-10-27 19:36:44.132401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0cedf175eb'
down_revision = '88e4d7bd8262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('working_hours', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_column('working_hours')

    # ### end Alembic commands ###
