"""New Fixes

Revision ID: bd8a43184b42
Revises: b645b0a772ef
Create Date: 2025-11-11 18:15:11.512551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd8a43184b42'
down_revision = 'b645b0a772ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('total_credits', sa.Float(), nullable=True),
    sa.Column('used_credits', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cs_eligibility', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('cs_eligibility')

    op.drop_table('leave_credit')
    # ### end Alembic commands ###
