"""Split address into barangay, municipality, province, postal_code, street_address

Revision ID: dd1972c3d54f
Revises: 95bb6eb72a3f
Create Date: 2025-11-08 10:59:52.443612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd1972c3d54f'
down_revision = '95bb6eb72a3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barangay', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('municipality', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('province', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('street_address', sa.String(length=255), nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.TEXT(), nullable=True))
        batch_op.drop_column('street_address')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('province')
        batch_op.drop_column('municipality')
        batch_op.drop_column('barangay')

    # ### end Alembic commands ###
